__rethrow_casa_exceptions = True
context = h_init()
context.set_state('ProjectSummary', 'proposal_code', '2017.1.00685.S')
context.set_state('ProjectSummary', 'piname', 'unknown')
context.set_state('ProjectSummary', 'proposal_title', 'unknown')
context.set_state('ProjectStructure', 'ous_part_id', 'X1943058409')
context.set_state('ProjectStructure', 'ous_title', 'Undefined')
context.set_state('ProjectStructure', 'ppr_file', '/opt/dared/opt/dared.2018OCT/mnt/dataproc/2017.1.00685.S_2019_01_22T17_35_03.598/SOUS_uid___A001_X1284_X113f/GOUS_uid___A001_X1284_X1140/MOUS_uid___A001_X1284_X1141/working/PPR_uid___A001_X1284_X1142.xml')
context.set_state('ProjectStructure', 'ps_entity_id', 'uid://A001/X1220/X80d')
context.set_state('ProjectStructure', 'recipe_name', 'hifa_cal')
context.set_state('ProjectStructure', 'ous_entity_id', 'uid://A001/X1220/X809')
context.set_state('ProjectStructure', 'ousstatus_entity_id', 'uid://A001/X1284/X1141')
try:
    hifa_importdata(vis=['uid___A002_Xd16a1e_X4327', 'uid___A002_Xd1c06f_X545c', 'uid___A002_Xd271e2_X9680', 'uid___A002_Xd271e2_X9993', 'uid___A002_Xd395f6_X1401a', 'uid___A002_Xd3c7c2_Xa6f1', 'uid___A002_Xd3c7c2_Xb7f9'], dbservice=False, session=['session_2', 'session_3', 'session_5', 'session_5', 'session_6', 'session_7', 'session_8'])
    hifa_flagdata(pipelinemode="automatic")
    hifa_fluxcalflag(pipelinemode="automatic")
    hif_rawflagchans(pipelinemode="automatic")
    hif_refant(pipelinemode="automatic")
    h_tsyscal(pipelinemode="automatic")
    hifa_tsysflag(pipelinemode="automatic")
    hifa_antpos(pipelinemode="automatic")
    hifa_wvrgcalflag(pipelinemode="automatic")
    hif_lowgainflag(pipelinemode="automatic")
    hif_setmodels(pipelinemode="automatic")
    hifa_bandpassflag(pipelinemode="automatic")
    hifa_spwphaseup(pipelinemode="automatic")
    hifa_gfluxscaleflag(pipelinemode="automatic")
    hifa_gfluxscale(pipelinemode="automatic")
    hifa_timegaincal(pipelinemode="automatic")
    hif_applycal(pipelinemode="automatic")
    hif_makeimlist(intent='PHASE,BANDPASS')
    hif_makeimages(pipelinemode="automatic")
    hif_makeimlist(per_eb=True, intent='CHECK')
    hif_makeimages(pipelinemode="automatic")
    hifa_imageprecheck(pipelinemode="automatic")
    hif_checkproductsize(maxproductsize=350.0, maxcubesize=40.0, maxcubelimit=60.0)
finally:
    h_save()
